#!/usr/bin/env bash
# debugging nginx port 80
# solved by deleting the existing ../sites-enabled/default then replace it with a copy of
# ../sites-available/default  by creating a symbolic link. 
# The flag -s creates a symbolic link, -f deletes the existing file and replaces it
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
